[package]
name = "dcgan-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
tch = "0.15.0"
#torch-sys = {version="0.15.0", features=["download-libtorch"]}
